name = "stm32_svd"
description = "SVD definitions for the stm32"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/wolfbiters/stm32_svd"

authors = ["wolf biters"]
maintainers = ["wolf biters <the.wolf.biters@gmail.com>"]
maintainers-logins = ["wolfbiters"]

[[depends-on]]
gnat_arm_elf = "^12"
beta_types = "1.0.0"

[configuration.variables]
runtime = { type = "Enum", values = ["embedded"], default = "embedded" }
board = { type = "Enum", values = ["stm32f429disco"], default = "stm32f429disco" }
