name = "stm32_svd"
description = "SVD definitions for the stm32"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/ohenley/stm32_svd"

authors = ["AdaCore"]
maintainers = ["olivier henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
gnat_arm_elf = "^12"
stm32_config = "1.0.0"
beta_types = "1.0.0"
